language: php

php:
- 5.5.9

services:
  - mysql

before_script:
  - composer update
  - mysql -e 'create database schema_test;'
  - mysql -e 'create database schema_test_2;'
  - cp -R ./vendor/laravel/laravel/* .
  - cp -R ./config/composer-laravel.json ./composer.json
  - cp -R ./config/phpunit.xml .
  - cp -R ./src/Schema/Console/Kernel.php ./app/Console/
  - cp -R ./config/database.php ./config/database.php
  - composer update
  - composer install --prefer-source --no-interaction --dev

script:
  - vendor/bin/phpunit --configuration phpunit.xml

notifications:
  on_success: always
  on_failure: always
